services:
  front:
    container_name: Masterise-front
    build:
      context: ./front
      dockerfile: Dockerfile
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
  back:
    container_name: Masterise-back
    build: ./back
    command: sh -c "tsc && node build/index.js"
    expose:
      - 5000
    volumes:
      - "./back/src:/app/src"
    environment:
      - MONGODB=mongodb://mongodb:27017/masterize
    env_file:
      - "./back/.env"

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:1.21.3
    depends_on:
      - back
      - front
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build:
