name: MasterizeCI

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  test_and_build_back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test the back before build it
        run: cd back && yarn && yarn test
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          MONGODB_ATLAS: ${{ secrets.MONGODB_ATLAS}}
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: theodorelefrancois/back:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test_and_build_front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test the front before build it
        run: cd front && yarn && yarn test
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          REACT_APP_API_DEV: ${{secrets.REACT_APP_API_DEV}}
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: theodorelefrancois/front:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
